#!/usr/bin/env node
//
// Writes the comparison table into the two places that publish it, from the one
// place that holds it: tools/comparison.json.
//
//   node tools/comparison.mjs            # write docs/comparison.html and README.md
//   node tools/comparison.mjs --check    # fail if either is out of date
//
// It exists because the table is published TWICE and its content rots: prices
// change, a version ships, a vendor rewrites a feature list. Two copies edited
// by hand disagree with each other long before either disagrees with the world,
// and nothing says so — this repository has the scar already, in a test that
// carried a copied sample of gosnmp's debug output and claimed
// SecurityModel:UserSecurityModel years after gosnmp had stopped printing it.
//
// So: one source, two renderings, and a test that fails when either drifts.
// The --check mode is what CI runs, in the shape tools/sitemap-lastmod.mjs
// established.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const DATA = join(root, 'tools', 'comparison.json');
const PAGE = join(root, 'docs', 'comparison.html');
const README = join(root, 'README.md');

const START = '<!-- comparison:start -->';
const END = '<!-- comparison:end -->';

// Generated blocks carry this, so that whoever opens the file to fix a price is
// told where the price actually lives before they type into the wrong one.
const WARNING = 'Generated by tools/comparison.mjs from tools/comparison.json — do not edit by hand.';

const data = JSON.parse(readFileSync(DATA, 'utf8'));

/** The products, in the order the data declares them. SnmpLens is first because
 *  the table is on its own site; the others keep the order chosen there. */
const products = data.products;

/** A cell is a string or an object. Reading both through one function keeps the
 *  data file readable — most cells are two words and deserve no envelope. */
function cell(row, id) {
  const raw = row.cells[id];
  if (raw === undefined) throw new Error(`row "${row.label}" has no cell for ${id}`);
  return typeof raw === 'string' ? { text: raw } : raw;
}

const escapeHtml = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// A pipe inside a cell ends the column early and silently shifts every cell
// after it one to the left, which reads as a data error rather than a syntax one.
const escapeMd = (s) => s.replace(/\|/g, '\\|');

function renderHtml() {
  const head = products
    .map((p) => `<th scope="col"><a href="${p.href}">${escapeHtml(p.name)}</a></th>`)
    .join('\n          ');

  const body = data.rows
    .map((row) => {
      const cells = products
        .map((p) => {
          const c = cell(row, p.id);
          const kind = c.kind ? ` data-kind="${c.kind}"` : '';
          return `<td${kind}>${escapeHtml(c.text)}</td>`;
        })
        .join('\n            ');
      return `<tr>\n            <th scope="row">${escapeHtml(row.label)}</th>\n            ${cells}\n          </tr>`;
    })
    .join('\n          ');

  return `${START}
      <!-- ${WARNING} -->
      <div class="table-scroll">
        <table class="compare">
          <caption class="visually-hidden">SnmpLens compared with ${products
            .slice(1)
            .map((p) => p.name)
            .join(', ')}, as each product's own documentation described it on ${data.checked}</caption>
          <thead>
            <tr>
              <th scope="col">&nbsp;</th>
              ${head}
            </tr>
          </thead>
          <tbody>
          ${body}
          </tbody>
        </table>
      </div>
      <p class="sources">
        Every cell about another product is what that product's own documentation stated on
        <time datetime="${data.checked}">${data.checked}</time>:
        ${products
          .slice(1)
          .map((p) => `<a href="${p.href}">${escapeHtml(p.sourceLabel)}</a>`)
          .join(', ')}.
        <strong>“Not listed”</strong> means their feature list does not mention it — a fact about
        their documentation, not a claim about their software.
      </p>

      <h2 id="stronger">Where each of the others is stronger</h2>
      <p>
        A comparison in which one column wins every row is an advertisement. These are the
        reasons to choose one of the others, and they are real ones.
      </p>
      <dl class="strengths">
      ${data.strengths
        .map((s) => {
          const p = products.find((x) => x.id === s.product);
          if (!p) throw new Error(`strengths names an unknown product: ${s.product}`);
          return `  <dt><a href="${p.href}">${escapeHtml(p.name)}</a></dt>\n        <dd>${escapeHtml(
            s.text,
          )}</dd>`;
        })
        .join('\n        ')}
      </dl>

      <h2 id="net-snmp">And none of them replaces Net-SNMP</h2>
      <p>${escapeHtml(data.baseline).replace(
        /`([^`]+)`/g,
        '<code>$1</code>',
      )}</p>
      ${END}`;
}

function renderMarkdown() {
  const header = `| | ${products.map((p) => `**${p.name}**`).join(' | ')} |`;
  const rule = `| --- | ${products.map(() => '---').join(' | ')} |`;

  const rows = data.rows
    .map((row) => {
      const cells = products
        .map((p) => {
          const c = cell(row, p.id);
          return escapeMd(c.short ?? c.text);
        })
        .join(' | ');
      return `| **${escapeMd(row.label)}** | ${cells} |`;
    })
    .join('\n');

  const sources = products
    .slice(1)
    .map((p) => `[${p.sourceLabel}](${p.href})`)
    .join(', ');

  return `${START}
<!-- ${WARNING} -->

${header}
${rule}
${rows}

Every cell about another product is what that product's own documentation stated on **${data.checked}**:
${sources}. "Not listed" means their feature list does not mention it — a fact about their
documentation, not a claim about their software. The long form, with what each of them is better
at, is on [the comparison page](https://snmplens.com/comparison.html).
${END}`;
}

/** Replace the region between the markers, and refuse a file that has none:
 *  appending the table to a file that lost its markers would publish it twice. */
function splice(file, block) {
  const body = readFileSync(file, 'utf8');
  const from = body.indexOf(START);
  const to = body.indexOf(END);
  if (from < 0 || to < 0) {
    throw new Error(`${file} has no ${START} … ${END} markers`);
  }
  return body.slice(0, from) + block + body.slice(to + END.length);
}

/** The two publications, each with the block it should currently hold.
 *  Exported so that the test asks THIS, rather than a second implementation of
 *  it that would agree with the generator and not with the files. */
export function targets() {
  return [
    { file: PAGE, name: 'docs/comparison.html', block: renderHtml() },
    { file: README, name: 'README.md', block: renderMarkdown() },
  ];
}

/** Which publications no longer match the data. Empty means both are current. */
export function outOfDate() {
  return targets().filter((t) => splice(t.file, t.block) !== readFileSync(t.file, 'utf8'));
}

export { data };

// Run as a command rather than imported. `process.argv[1]` is the script node
// was given; comparing the resolved paths is what tells the two apart.
const invoked = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invoked) {
  const check = process.argv.includes('--check');
  const stale = outOfDate();

  for (const t of stale) {
    if (check) {
      console.error(`comparison: ${t.name} is out of date`);
    } else {
      writeFileSync(t.file, splice(t.file, t.block));
      console.log(`comparison: wrote ${t.name}`);
    }
  }

  if (check) {
    if (stale.length) {
      console.error('\nRun: node tools/comparison.mjs');
      process.exit(1);
    }
    console.log(`comparison: both renderings match tools/comparison.json (checked ${data.checked}).`);
  } else if (!stale.length) {
    console.log('comparison: both renderings were already up to date.');
  }
}
